configuracion:
    
    servidor:
#        appserver: unicorn
#        puerto: 3000
#        binding: localhost
#        entorno: development
#        worker_processes: 2
#        timeout: 120

    aplicacion:
#        host: localhost
#        url: http://localhost:3000
#        titulo: 'cuman&aacute; web services'
#        eslogan: ''
#        descripcion: ''
#        etiquetas: 'dominios, registro de dominios, hospedaje web, alojamiento web, hosting, web hosting'
#        favicon_src: 'favicon.png'
#        logo_src: ''
#        resumen: '<!--[if lte IE 8]><span style="filter: FlipH; -ms-filter: "FlipH"; display: inline-block;"><![endif]-->
#                    <span style="-moz-transform: scaleX(-1); -o-transform: scaleX(-1); -webkit-transform: scaleX(-1); transform: scaleX(-1); display: inline-block;">
#                        &copy;
#                    </span>
#                    <!--[if lte IE 8]></span><![endif]-->
#                    2015 cuman&aacute; web services'
#
#        ns:
#            ip:
#            host:
#            mail:
#
#        db:
#            pgsql:
#                user: postgres
#                password: postgres
#            mysql:
#                user: mysql
#                password: mysql
#            mongodb:
#                user: mongo
#                password: mongo
#                
#        paypal:
#            id:
#            
#        bitcoin:
#            direccion:
        
development:

production: